/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as E001153aEa554aaf939aFeac4a3aea86RouteImport } from './routes/e001153a-ea55-4aaf-939a-feac4a3aea86'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppWithdrawalsRouteImport } from './routes/app/withdrawals'
import { Route as AppWithdrawRouteImport } from './routes/app/withdraw'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as AppReferralRouteImport } from './routes/app/referral'
import { Route as AppDepositRouteImport } from './routes/app/deposit'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin/withdrawals'
import { Route as AdminGlobalWalletRouteImport } from './routes/admin/global-wallet'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminBatchCollectRouteImport } from './routes/admin/batch-collect'

const E001153aEa554aaf939aFeac4a3aea86Route =
  E001153aEa554aaf939aFeac4a3aea86RouteImport.update({
    id: '/e001153a-ea55-4aaf-939a-feac4a3aea86',
    path: '/e001153a-ea55-4aaf-939a-feac4a3aea86',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppWithdrawalsRoute = AppWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralRoute = AppReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRoute = AppDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGlobalWalletRoute = AdminGlobalWalletRouteImport.update({
  id: '/global-wallet',
  path: '/global-wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchCollectRoute = AdminBatchCollectRouteImport.update({
  id: '/batch-collect',
  path: '/batch-collect',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/e001153a-ea55-4aaf-939a-feac4a3aea86': typeof E001153aEa554aaf939aFeac4a3aea86Route
  '/admin/batch-collect': typeof AdminBatchCollectRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/global-wallet': typeof AdminGlobalWalletRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/referral': typeof AppReferralRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app/withdrawals': typeof AppWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/e001153a-ea55-4aaf-939a-feac4a3aea86': typeof E001153aEa554aaf939aFeac4a3aea86Route
  '/admin/batch-collect': typeof AdminBatchCollectRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/global-wallet': typeof AdminGlobalWalletRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/referral': typeof AppReferralRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app/withdrawals': typeof AppWithdrawalsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/e001153a-ea55-4aaf-939a-feac4a3aea86': typeof E001153aEa554aaf939aFeac4a3aea86Route
  '/admin/batch-collect': typeof AdminBatchCollectRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/global-wallet': typeof AdminGlobalWalletRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/referral': typeof AppReferralRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app/withdrawals': typeof AppWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/app'
    | '/e001153a-ea55-4aaf-939a-feac4a3aea86'
    | '/admin/batch-collect'
    | '/admin/dashboard'
    | '/admin/global-wallet'
    | '/admin/withdrawals'
    | '/app/dashboard'
    | '/app/deposit'
    | '/app/referral'
    | '/app/transactions'
    | '/app/withdraw'
    | '/app/withdrawals'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/e001153a-ea55-4aaf-939a-feac4a3aea86'
    | '/admin/batch-collect'
    | '/admin/dashboard'
    | '/admin/global-wallet'
    | '/admin/withdrawals'
    | '/app/dashboard'
    | '/app/deposit'
    | '/app/referral'
    | '/app/transactions'
    | '/app/withdraw'
    | '/app/withdrawals'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/app'
    | '/e001153a-ea55-4aaf-939a-feac4a3aea86'
    | '/admin/batch-collect'
    | '/admin/dashboard'
    | '/admin/global-wallet'
    | '/admin/withdrawals'
    | '/app/dashboard'
    | '/app/deposit'
    | '/app/referral'
    | '/app/transactions'
    | '/app/withdraw'
    | '/app/withdrawals'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  E001153aEa554aaf939aFeac4a3aea86Route: typeof E001153aEa554aaf939aFeac4a3aea86Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/e001153a-ea55-4aaf-939a-feac4a3aea86': {
      id: '/e001153a-ea55-4aaf-939a-feac4a3aea86'
      path: '/e001153a-ea55-4aaf-939a-feac4a3aea86'
      fullPath: '/e001153a-ea55-4aaf-939a-feac4a3aea86'
      preLoaderRoute: typeof E001153aEa554aaf939aFeac4a3aea86RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/withdrawals': {
      id: '/app/withdrawals'
      path: '/withdrawals'
      fullPath: '/app/withdrawals'
      preLoaderRoute: typeof AppWithdrawalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/withdraw': {
      id: '/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referral': {
      id: '/app/referral'
      path: '/referral'
      fullPath: '/app/referral'
      preLoaderRoute: typeof AppReferralRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deposit': {
      id: '/app/deposit'
      path: '/deposit'
      fullPath: '/app/deposit'
      preLoaderRoute: typeof AppDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/global-wallet': {
      id: '/admin/global-wallet'
      path: '/global-wallet'
      fullPath: '/admin/global-wallet'
      preLoaderRoute: typeof AdminGlobalWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batch-collect': {
      id: '/admin/batch-collect'
      path: '/batch-collect'
      fullPath: '/admin/batch-collect'
      preLoaderRoute: typeof AdminBatchCollectRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBatchCollectRoute: typeof AdminBatchCollectRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGlobalWalletRoute: typeof AdminGlobalWalletRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBatchCollectRoute: AdminBatchCollectRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGlobalWalletRoute: AdminGlobalWalletRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepositRoute: typeof AppDepositRoute
  AppReferralRoute: typeof AppReferralRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppWithdrawalsRoute: typeof AppWithdrawalsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDepositRoute: AppDepositRoute,
  AppReferralRoute: AppReferralRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppWithdrawalsRoute: AppWithdrawalsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  E001153aEa554aaf939aFeac4a3aea86Route: E001153aEa554aaf939aFeac4a3aea86Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
